import Hero from "./Hero/Hero";
import Features from "./Features/Features";
import About from "./About/About";
import Testimonials from "./Testimonials/Testimonials";
import Contact from "./Contact/Contact";
import Navbar from "./Navbar/Navbar";
import Footer from "./Footer/Footer";
import StudentNavbar from "./Dashboard/StudentNavbar/StudentNavbar";
import ContactForm from "./Dashboard/ContactForm/ContactForm";
import CourseDetailsModal from "./Dashboard/CourseDetailsModal/CourseDetailsModal";
import CourseRegistration from "./Dashboard/CourseRegistration/CourseRegistration";
import ProfileInfo from "./Dashboard/ProfileInfo/ProfileInfo";
import SelectedCourses from "./Dashboard/SelectedCourses/SelectedCourses";
import Sidebar from "./Dashboard/Sidebar/Sidebar";
import AdminSidebar from "./Admin-Components/AdminSidebar/AdminSidebar";
import CourseManager from "./Admin-Components/CourseManager/CourseManager";
import ProfileCard from "./Admin-Components/ProfileCard/ProfileCard";
import StudentList from "./Admin-Components/StudentList/StudentList";
import TopNavbar from "./Admin-Components/TopNavbar/TopNavbar";

export { Hero, Features, About, Testimonials, Contact, Navbar, Footer, StudentNavbar, ContactForm, CourseDetailsModal, CourseRegistration, ProfileInfo, SelectedCourses, Sidebar, AdminSidebar, CourseManager, ProfileCard, StudentList, TopNavbar };